title = "Climate Tools"
baseurl = "https://cbtooltest.marisa.psu.edu/"
languageCode = "en"
theme = "soho"
googleAnalytics = "UA-114998663-2"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = false

[params]
description = ""
# gravatar = "soho@example.com"
# profileImage = "https://standard.psu.edu/images/uploads/psu-mark.svg"
profileImage = "https://wwwassets.rand.org/content/dam/marisa/logo-marisa.svg"
copyright = "EESI Team"
phone = "1-555-555-1234"
email = "mdl5548@psu.edu"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[menu]

  [[menu.main]]
  name = "Tools"
  weight = 100
  identifier = "tools"
  url = "/tools/"

  [[menu.main]]
  name = "Tool Search"
  weight = 200
  identifier = "toolsearch"
  url = "/toolsearch/"

  [[menu.main]]
  name = "Glossary"
  weight = 300
  identifier = "glossary"
  url = "/glossary/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "JSON"]
